<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="zhaocongdeAir.lan" name="cn.nhsoft.amazoncloud.apitest.systembooklist.SystembookListTest" tests="6" failures="1" timestamp="1 Jun 2020 13:28:41 GMT" time="1.458" errors="0">
  <testcase name="testQuery_code_exists" time="0.069" classname="cn.nhsoft.amazoncloud.apitest.systembooklist.SystembookListTest"/>
  <testcase name="testQuery_code_notexists_1111" time="0.049" classname="cn.nhsoft.amazoncloud.apitest.systembooklist.SystembookListTest">
    <failure type="junit.framework.ComparisonFailure" message="null expected:&lt;200[1]05&gt; but was:&lt;200[]05&gt;">
      <![CDATA[junit.framework.ComparisonFailure: null expected:<200[1]05> but was:<200[]05>
	at junit.framework.Assert.assertEquals(Assert.java:81)
	at junit.framework.Assert.assertEquals(Assert.java:87)
	at cn.nhsoft.amazoncloud.apitest.systembooklist.SystembookListTest.testQuery_code_notexists_1111(SystembookListTest.java:130)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- testQuery_code_notexists_1111 -->
  <testcase name="testQuery_code_exists" time="1.222" classname="cn.nhsoft.amazoncloud.apitest.systembooklist.SystembookListTest"/>
  <testcase name="testQuery_feed_1" time="0.036" classname="cn.nhsoft.amazoncloud.apitest.systembooklist.SystembookListTest"/>
  <testcase name="testQuery_feed_1" time="0.038" classname="cn.nhsoft.amazoncloud.apitest.systembooklist.SystembookListTest"/>
  <testcase name="testQuery_feed_1" time="0.044" classname="cn.nhsoft.amazoncloud.apitest.systembooklist.SystembookListTest"/>
</testsuite> <!-- cn.nhsoft.amazoncloud.apitest.systembooklist.SystembookListTest -->
